### ISSUE TITLE
_reactDom2.default.findDOMNode is not a function

### ISSUE THREAD

**Issue by estorski** [okonet/react-container-dimensions#14]
Hey everyone,

I'm trying to use the react-container-dimensions package with @kadira/storyshots testing approach (an addition to the storybook), however launching the tests results in this error:
_reactDom2.default.findDOMNode is not a function
at ContainerDimensions.componentDidMount (...\node_modules\react-container-dimensions\lib\index.js:69:50)

Meanwhile all the components that do not use the package render successfully.

It feels like a configuration issue. Does anyone have an idea how to fix it?

**Comment by mjhm** [comment]
I'm seeing a related issue using Storyshots

```
Invariant Violation: getNodeFromInstance: Invalid argument.
      
      at invariant (node_modules/fbjs/lib/invariant.js:44:15)
      at Object.getNodeFromInstance (node_modules/react-dom/lib/ReactDOMComponentTree.js:162:77)
      at Object.findDOMNode (node_modules/react-dom/lib/findDOMNode.js:49:41)
      at ContainerDimensions.componentDidMount (node_modules/react-container-dimensions/lib/index.js:72:44)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:206:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:153:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.render (node_modules/react-test-renderer/lib/ReactTestMount.js:125:18)
      at Object.test (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:21:44)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:148:25)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

Apparently there is a related fix implemented in https://github.com/souporserious/react-measure/issues/35

**Comment by okonet** [comment]
Should this be fixed in this lib? PR is more than welcome!

**Comment by mjhm** [comment]
I dunno. It looks like the approach for `react-measure` was to entirely avoid `findDOMNode` and use a `ref` instead.  That required a change to `react-measure` and some changes to its usage.  Since I wasn't heavily invested in `react-container-dimensions` I ended up switching to `react-measure` which worked for my limited use case.

**Comment by spsaucier** [comment]
With storyshots now, it's getting kicked out by ContainerDimensions directly - `At least one element required.`
